import { createRoot } from 'react-dom/client'
import App from '@/App'
import '@/css/source-item.css'
import '@/css/sources-list.css'
import '@/css/confirm-window.css'
import '@/css/add-source-bar.css'
import '@/css/header.css'
import '@/css/root.css'
import '@/css/add-prediction-bar.css'
import '@/css/prediction-item.css'
import '@/css/predictions-list.css'
import '@/css/timer.css'
import '@/css/asset-item.css'
import '@/css/assets-list.css'
import '@/css/total-money-chart.css'
import '@/css/set-path-bar.css'
import '@/css/anime-list.css'
import '@/css/anime-item.css'
import '@/css/anime-play-header.css'
import '@/css/anime-play-page.css'
import '@/css/custom-video-player.css'
import '@/css/episode-selector.css'

createRoot(document.getElementById('root')!).render(<App />)
